package dao;
// Generated 2019-09-29 13:35:30 by Hibernate Tools 4.3.1



/**
 * Articlecommande generated by hbm2java
 */
public class Articlecommande  implements java.io.Serializable {


     private ArticlecommandeId id;
     private Commande commandeByNoarticle;
     private Commande commandeByNocommande;
     private Boolean quantite;

    public Articlecommande() {
    }

	
    public Articlecommande(ArticlecommandeId id, Commande commandeByNoarticle, Commande commandeByNocommande) {
        this.id = id;
        this.commandeByNoarticle = commandeByNoarticle;
        this.commandeByNocommande = commandeByNocommande;
    }
    public Articlecommande(ArticlecommandeId id, Commande commandeByNoarticle, Commande commandeByNocommande, Boolean quantite) {
       this.id = id;
       this.commandeByNoarticle = commandeByNoarticle;
       this.commandeByNocommande = commandeByNocommande;
       this.quantite = quantite;
    }
   
    public ArticlecommandeId getId() {
        return this.id;
    }
    
    public void setId(ArticlecommandeId id) {
        this.id = id;
    }
    public Commande getCommandeByNoarticle() {
        return this.commandeByNoarticle;
    }
    
    public void setCommandeByNoarticle(Commande commandeByNoarticle) {
        this.commandeByNoarticle = commandeByNoarticle;
    }
    public Commande getCommandeByNocommande() {
        return this.commandeByNocommande;
    }
    
    public void setCommandeByNocommande(Commande commandeByNocommande) {
        this.commandeByNocommande = commandeByNocommande;
    }
    public Boolean getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Boolean quantite) {
        this.quantite = quantite;
    }




}


