package dao;
// Generated 2019-09-29 13:35:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private long noarticle;
     private String marque;
     private String categorie;
     private String description;
     private BigDecimal prixunitaire;
     private short quantiteenstock;
     private Boolean ensolde;

    public Article() {
    }

	
    public Article(long noarticle, String marque, String categorie, String description, BigDecimal prixunitaire, short quantiteenstock) {
        this.noarticle = noarticle;
        this.marque = marque;
        this.categorie = categorie;
        this.description = description;
        this.prixunitaire = prixunitaire;
        this.quantiteenstock = quantiteenstock;
    }
    public Article(long noarticle, String marque, String categorie, String description, BigDecimal prixunitaire, short quantiteenstock, Boolean ensolde) {
       this.noarticle = noarticle;
       this.marque = marque;
       this.categorie = categorie;
       this.description = description;
       this.prixunitaire = prixunitaire;
       this.quantiteenstock = quantiteenstock;
       this.ensolde = ensolde;
    }
   
    public long getNoarticle() {
        return this.noarticle;
    }
    
    public void setNoarticle(long noarticle) {
        this.noarticle = noarticle;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getPrixunitaire() {
        return this.prixunitaire;
    }
    
    public void setPrixunitaire(BigDecimal prixunitaire) {
        this.prixunitaire = prixunitaire;
    }
    public short getQuantiteenstock() {
        return this.quantiteenstock;
    }
    
    public void setQuantiteenstock(short quantiteenstock) {
        this.quantiteenstock = quantiteenstock;
    }
    public Boolean getEnsolde() {
        return this.ensolde;
    }
    
    public void setEnsolde(Boolean ensolde) {
        this.ensolde = ensolde;
    }




}


