package dao;
// Generated 2019-09-29 13:35:30 by Hibernate Tools 4.3.1



/**
 * ArticlecommandeId generated by hbm2java
 */
public class ArticlecommandeId  implements java.io.Serializable {


     private long nocommande;
     private long noarticle;

    public ArticlecommandeId() {
    }

    public ArticlecommandeId(long nocommande, long noarticle) {
       this.nocommande = nocommande;
       this.noarticle = noarticle;
    }
   
    public long getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(long nocommande) {
        this.nocommande = nocommande;
    }
    public long getNoarticle() {
        return this.noarticle;
    }
    
    public void setNoarticle(long noarticle) {
        this.noarticle = noarticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticlecommandeId) ) return false;
		 ArticlecommandeId castOther = ( ArticlecommandeId ) other; 
         
		 return (this.getNocommande()==castOther.getNocommande())
 && (this.getNoarticle()==castOther.getNoarticle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNocommande();
         result = 37 * result + (int) this.getNoarticle();
         return result;
   }   


}


