package dao;
// Generated 2019-09-29 13:35:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private long noclient;
     private String nomclient;
     private String motdepasse;
     private String emailclient;
     private Set commandes = new HashSet(0);

    public Client() {
    }

	
    public Client(long noclient, String nomclient, String motdepasse, String emailclient) {
        this.noclient = noclient;
        this.nomclient = nomclient;
        this.motdepasse = motdepasse;
        this.emailclient = emailclient;
    }
    public Client(long noclient, String nomclient, String motdepasse, String emailclient, Set commandes) {
       this.noclient = noclient;
       this.nomclient = nomclient;
       this.motdepasse = motdepasse;
       this.emailclient = emailclient;
       this.commandes = commandes;
    }
   
    public long getNoclient() {
        return this.noclient;
    }
    
    public void setNoclient(long noclient) {
        this.noclient = noclient;
    }
    public String getNomclient() {
        return this.nomclient;
    }
    
    public void setNomclient(String nomclient) {
        this.nomclient = nomclient;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public String getEmailclient() {
        return this.emailclient;
    }
    
    public void setEmailclient(String emailclient) {
        this.emailclient = emailclient;
    }
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


