package dao;
// Generated 2019-09-29 13:35:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private long nocommande;
     private Client client;
     private Date datecommande;
     private Set articlecommandesForNoarticle = new HashSet(0);
     private Set articlecommandesForNocommande = new HashSet(0);

    public Commande() {
    }

	
    public Commande(long nocommande) {
        this.nocommande = nocommande;
    }
    public Commande(long nocommande, Client client, Date datecommande, Set articlecommandesForNoarticle, Set articlecommandesForNocommande) {
       this.nocommande = nocommande;
       this.client = client;
       this.datecommande = datecommande;
       this.articlecommandesForNoarticle = articlecommandesForNoarticle;
       this.articlecommandesForNocommande = articlecommandesForNocommande;
    }
   
    public long getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(long nocommande) {
        this.nocommande = nocommande;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }
    public Set getArticlecommandesForNoarticle() {
        return this.articlecommandesForNoarticle;
    }
    
    public void setArticlecommandesForNoarticle(Set articlecommandesForNoarticle) {
        this.articlecommandesForNoarticle = articlecommandesForNoarticle;
    }
    public Set getArticlecommandesForNocommande() {
        return this.articlecommandesForNocommande;
    }
    
    public void setArticlecommandesForNocommande(Set articlecommandesForNocommande) {
        this.articlecommandesForNocommande = articlecommandesForNocommande;
    }




}


